#!/bin/bash
#Funnyvpn
#Rerechan02
#Rayzell25
#Nuralfiya
#em0zz
#naravpn.com
#indo-ssh.com
#indossh
#Skc
vlx=$(grep -c -E "^#& " "/etc/xray/config.json")
let vla=$vlx/2
vmc=$(grep -c -E "^### " "/etc/xray/config.json")
let vma=$vmc/4
ssh1="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
trx=$(grep -c -E "^#! " "/etc/xray/config.json")
let tra=$trx/2
clear
#=========================================================================================================================
#EXPIRED
xp    
y='\033[1;33m' #yellow
BGX="\033[42m"
CYAN="\033[96m"
z="\033[96m"
RED='\033[0;31m'
NC='\033[0m'
gray="\e[1;30m"
Blue="\033[0;34m"
green='\033[0;32m'
grenbo="\e[92;1m"
purple="\033[1;95m"
YELL='\033[0;33m'
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33;1m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
ori='\e[32;1m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
echo 1 > /proc/sys/vm/drop_caches
run_izin() {
  # Link izin IP VPS
  url_izin='https://raw.githubusercontent.com/SETANTAZVPN/mlbb/main/izin.txt'

  # Mendapatkan IP VPS saat ini
  ip_vps=$(curl -sS ipinfo.io/ip)

  # Mendapatkan isi file izin.txt dari URL
  izin=$(curl -s "$url_izin")

  # Memeriksa apakah konten izin.txt berhasil didapatkan
  if [[ -n "$izin" ]]; then
    while IFS= read -r line; do
      # Memisahkan nama VPS, IP VPS, dan tanggal kadaluwarsa
      nama=$(echo "$line" | awk '{print $1}')
      ipvps=$(echo "$line" | awk '{print $2}')
      tanggal=$(echo "$line" | awk '{print $3}')

      # Memeriksa apakah IP VPS saat ini cocok dengan IP VPS yang ada di izin.txt
      if [[ "$ipvps" == "$ip_vps" ]]; then
        echo "Nama VPS: $nama"
        echo "IP VPS: $ipvps"
        echo "Tanggal Kadaluwarsa: $tanggal"
        break
      fi
    done <<< "$izin"

    # Memeriksa apakah IP VPS ditemukan dalam izin.txt
    if [[ "$ipvps" != "$ip_vps" ]]; then
      # Add your message here for when the VPS doesn't have permission
clear
      echo -e "\e[33m ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m" | lolcat
      echo -e "                 • Rerechan Store •                 "
      echo -e "\e[33m ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m" | lolcat
      echo -e ""
      echo -e "\e[93m Nama\e[32;1m   : $nama "
      echo -e "\e[93m IP VPS\e[32;1m : $ip_vps"
      echo -e "\e[93m Domain\e[32;1m : $(cat /etc/xray/domain)"
      echo -e ""
      echo -e "\e[93m Ssh\e[32;1m    : STOPPED "
      echo -e "\e[93m Trojan\e[32;1m : STOPPED "
      echo -e "\e[93m Vless\e[32;1m  : STOPPED "
      echo -e "\e[93m Vmess\e[32;1m  : STOPPED "
      echo -e ""        
      echo -e "${red} VPS Anda Tidak Izinkan \e[32;1m "
      echo -e "${red} Contact Admin Untuk Perizinan \e[32;1m" | lolcat
      echo -e ""
      echo -e "\e[93m Telegram\e[32;1m : https://t.me/Rerechan02"
      echo -e "\e[33m ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m" | lolcat
      echo -e ""
      exit 0
    fi
  else
    echo "Konten izin.txt tidak berhasil didapatkan dari URL"
    exit 0
  fi
  clear
}
run_izin
clear
run_exp() {
xp
}      
# Color Validation
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
# VPS Information
TIMEZONE=$(printf '%(%H:%M:%S)T')
#Domain
domain=$(cat /etc/xray/domain)
# OS Uptime
uptime="$(uptime -p | cut -d " " -f 2-10)"
# Download
ISP=$(cat /root/.myisp)
CITY=$(cat /root/.mycity)
DATE2=$(date -R | cut -d " " -f -5)
IPVPS=$(cat /root/.myip)
clear
#Download/Upload today
dtoday="$(vnstat -i eth0 | grep "today" | awk '{print $2" "substr ($3, 1, 1)}')"
utoday="$(vnstat -i eth0 | grep "today" | awk '{print $5" "substr ($6, 1, 1)}')"
ttoday="$(vnstat -i eth0 | grep "today" | awk '{print $8" "substr ($9, 1, 1)}')"
#Download/Upload yesterday
dyest="$(vnstat -i eth0 | grep "yesterday" | awk '{print $2" "substr ($3, 1, 1)}')"
uyest="$(vnstat -i eth0 | grep "yesterday" | awk '{print $5" "substr ($6, 1, 1)}')"
tyest="$(vnstat -i eth0 | grep "yesterday" | awk '{print $8" "substr ($9, 1, 1)}')"
#Download/Upload current month
dmon="$(vnstat -i eth0 -m | grep "`date +"%b '%y"`" | awk '{print $3" "substr ($4, 1, 1)}')"
umon="$(vnstat -i eth0 -m | grep "`date +"%b '%y"`" | awk '{print $6" "substr ($7, 1, 1)}')"
tmon="$(vnstat -i eth0 -m | grep "`date +"%b '%y"`" | awk '{print $9" "substr ($10, 1, 1)}')"
clear
echo -e " ${z}╭══════════════════════════════════════════════════════════╮${NC}"
echo -e " ${z}│$NC\033[41m      .::::.  ℙ𝕒𝕟𝕖𝕝 𝕤𝕥𝕧𝕡 𝕊𝕥𝕠𝕣𝕖𝕤 .::::.       $NC${z}│$NC"
echo -e " ${z}╰══════════════════════════════════════════════════════════╯${NC}"
echo -e " ${z}╭══════════════════════════════════════════════════════════╮${NC}"
echo -e " ${z}│$NC$r ⇲ $NC$y 𝗦𝘆𝘀𝘁𝗲𝗺 𝗢𝗦 ${NC}     $Blue=$NC `hostnamectl | grep "Operating System" | cut -d ' ' -f5-`${NC}"
echo -e " ${z}│$NC$r ⇲ $NC$y 𝗨𝗽𝘁𝗶𝗺𝗲 𝗦𝗲𝗿𝘃𝗲𝗿 ${NC} $Blue=$NC $uptime${NC}"
echo -e " ${z}│$NC$r ⇲ $NC$y 𝗗𝗮𝘁𝗲 & 𝗧𝗶𝗺𝗲 ${NC}          $Blue=$NC $DATE2${NC}"
echo -e " ${z}│$NC$r ⇲ $NC$y 𝗧𝗶𝗺𝗲Zone ${NC}          $Blue=$NC $TIMEZONE${NC}"
echo -e " ${z}│$NC$r ⇲ $NC$y 𝗜𝗣 𝗩𝗣𝗦 ${NC}        $Blue=$NC $IPVPS${NC}"
echo -e " ${z}│$NC$r ⇲ $NC$y 𝗗𝗼𝗺𝗮𝗶𝗻 ${NC}        $Blue=$NC $domain${NC}"
echo -e " ${z}╰══════════════════════════════════════════════════════════╯${NC}"
echo -e " ${z}     ╭══════════════════════════════════════╮${NC}" | lolcat
echo -e "\e[33m       SSH / WS / UDP / DNS    : $ssh1"
echo -e "\e[33m       VMESS / WS / GRPC       : $vma"
echo -e "\e[33m       VLESS / WS / GRPC       : $vla"
echo -e "\e[33m       TROJAN / WS / GRPC      : $tra"
echo -e " ${z}      ╰══════════════════════════════════════╯${NC}" | lolcat
echo -e "                ${KIRI} ${purple}𝑰𝒏𝒇𝒐𝒓𝒎𝒂𝒔𝒊𝒐𝒏 𝑴𝒆𝒏𝒖${NC} ${KANAN}"
echo -e " ${z}╭══════════════════════════════════════════════════════════╮${NC}"
echo -e " ${z}│$NC [${r}01${NC}]$purple SSH MENU$NC     ${z}$NC [${r}09${NC}]$purple REBOOT$NC "
echo -e " ${z}│$NC [${r}02${NC}]$purple VMESS MENU$NC   ${z}$NC [${r}10${NC}]$purple RESTART$NC "    
echo -e " ${z}│$NC [${r}03${NC}]$purple VLESS MENU$NC   ${z}$NC [${r}11${NC}]$purple SUBDOMAIN$NC"   
echo -e " ${z}│$NC [${r}04${NC}]$purple TROJAN MENU$NC  ${z}$NC [${r}12${NC}]$purple CERT SSL$NC  " 
echo -e " ${z}│$NC [${r}05${NC}]$purple SPEEDTEST$NC  ${z}$NC    [${r}13${NC}]$purple RUNNING$NC"
echo -e " ${z}│$NC [${r}06${NC}]$purple BACKUP MENU$NC${z}$NC [${r}14${NC}]$purple EDIT BANNER$NC"
echo -e " ${z}│$NC [${r}07${NC}]$purple VPS INFO$NC     ${z}$NC [${r}15${NC}]$purple NSDOMIAN$NC"
echo -e " ${z}│$NC [${r}08${NC}]$purple RESTORE MENU$NC${z}$NC [${r}16${NC}]$purple SETTING MENU$NC"
echo -e " ${z}│                                                          $NC${z}$NC"
echo -e " ${z}│$NC [${r}00${NC}]$purple BACK TO EXIT MENU$NC ${KANAN} \E[0m\033[0;34m                              $NC${z}│$NC"
echo -e " ${z}╰══════════════════════════════════════════════════════════╯${NC}"
echo -e " ${z}╭══════════════════════════════════════════════════════════╮${NC}"
echo -e " ${z}│$NC$y ➪ 𝗩𝗲𝗿𝘀𝗶𝗼𝗻$NC       ${Blue}=$NC V1.0"
echo -e " ${z}│$NC$y ➪ 𝗨𝘀𝗲𝗿 $NC         ${Blue}=$NC $nama"
echo -e " ${z}│$NC$y ➪ 𝗘𝘅𝗽𝗶𝗿𝗲 𝗦𝗰𝗿𝗶𝗽𝘁 $NC$Blue=$green $tanggal$NC"
echo -e " ${z}╰══════════════════════════════════════════════════════════╯${NC}"
read -p " Silahkan pilih Menu :  "  opt
echo -e   ""
case $opt in
1) clear ; run_izin ; run_exp ; menu-ssh ;;
2) clear ; run_izin ; run_exp ; menu-vmess ;;
3) clear ; run_izin ; run_exp ; menu-vless ;;
4) clear ; run_izin ; run_exp ; menu-trojan ;;
5) clear ; run_izin ; run_exp ; speed ;;
6) clear ; run_izin ; run_exp ; backup ;;
7) clear ; run_izin ; run_exp ; about ;;
8) clear ; run_izin ; run_exp ; restore ;;
9) clear ; run_izin ; run_exp ; reboot ;;
10) clear ; run_izin ; run_exp ; restart ;;
11) clear ; run_izin ; run_exp ; add-host ;;
12) clear ; run_izin ; run_exp ; cert ;;
13) clear ; run_izin ; run_exp ; running ;;
14) clear ; run_izin ; run_exp ; nano /etc/issue.net ;;
15) clear ; run_izin ; run_exp ; dns ;;
16) clear ; run_izin ; run_exp ; menu-system ;;
0) clear ; run_izin ; run_exp ; menu ;;
x) exit ;;
*) echo "Anda salah tekan " ; sleep 1 ; menu ;;
esac
